### ISSUE TITLE
App Crash on accessing block explorer for Transactions, Addresses or Blocks

### ISSUE THREAD

**Issue by HashEngineering** [HashEngineering/myriadcoin-wallet#5]
The recent block explorer change is resulting in an exception. 

http://insight-myr.cryptap.us/block/db2fcb5bbd9c5165c8bf8a04b48a1891117a5b33f84f3ee33ae46f5ecc1cdad5

05-01 15:05:12.176 19092-19092/hashengineering.myriadcoin.wallet E/AndroidRuntime﹕ FATAL EXCEPTION: main
Process: hashengineering.myriadcoin.wallet, PID: 19092
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat= http://insight-myr.cryptap.us/block/db2fcb5bbd9c5165c8bf8a04b48a1891117a5b33f84f3ee33ae46f5ecc1cdad5 }
at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1660)
at android.app.Instrumentation.execStartActivity(Instrumentation.java:1430)
at android.app.Activity.startActivityForResult(Activity.java:3628)
at android.app.Activity.startActivityForResult(Activity.java:3589)
at android.support.v4.app.FragmentActivity.startActivityFromFragment(FragmentActivity.java:683)
at android.support.v4.app.Fragment.startActivity(Fragment.java:783)
at de.schildbach.wallet.ui.BlockListFragment$1.onActionItemClicked(BlockListFragment.java:170)
at com.actionbarsherlock.internal.ActionBarSherlockNative$ActionModeCallbackWrapper.onActionItemClicked(ActionBarSherlockNative.java:238)
at com.android.internal.policy.impl.PhoneWindow$DecorView$ActionModeCallbackWrapper.onActionItemClicked(PhoneWindow.java:3069)
at com.android.internal.app.ActionBarImpl$ActionModeImpl.onMenuItemSelected(ActionBarImpl.java:1081)
at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:741)
at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:884)
at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:874)
at com.android.internal.view.menu.MenuPopupHelper.onItemClick(MenuPopupHelper.java:231)
at android.widget.AdapterView.performItemClick(AdapterView.java:313)
at android.widget.AbsListView.performItemClick(AbsListView.java:1529)
at android.widget.AbsListView$PerformClick.run(AbsListView.java:3560)
at android.widget.AbsListView$3.run(AbsListView.java:5277)
at android.os.Handler.handleCallback(Handler.java:733)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:146)
at android.app.ActivityThread.main(ActivityThread.java:5635)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
at dalvik.system.NativeStart.main(Native Method)

**Comment by cryptapus** [comment]
Confirmed with your latest beta build. Not clear why there would be an exception. I would say you should revert to previous version until resolved, but the old explorer no longer exists...

**Comment by HashEngineering** [comment]
Instead of reverting, I would rather fix it with a working block Explorer
link.  There are a few explorers that have Myriad.  I will try to fix this
by tomorrow.   Thanks for all your help.

**Comment by HashEngineering** [comment]
This was the string found in myriadcoinj - " http://insight-myr.cryptap.us/" - there is a space before the "http".  That caused the exception.  I will roll out the release to Google Play and Github.

**Comment by HashEngineering** [comment]
https://github.com/HashEngineering/myriadcoin-wallet/releases/tag/v0.9.2.16b
